version: '3.8'
services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'