version: '3.8'
services:
  app:
    image: jamesfrj/movies:latest
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/movies
      - SPRING_DATASOURCE_USERNAME=movies
      - SPRING_DATASOURCE_PASSWORD=movies
  postgres:
    image: postgres:14.5-alpine
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movies
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U movies" ]
      interval: 10s
      timeout: 5s
      retries: 5